### ISSUE TITLE
Input file discarded (smaller than minTermSize) but still present in the heatmap

### ISSUE THREAD

**Issue by agroppi** [ozanozisik/orsum#10]
Here are my input files : [Orsum_input_files.zip](https://github.com/ozanozisik/orsum/files/14178150/Orsum_input_files.zip)

My command line : 
`./python3 orsum.py --gmt '/home/ag/Enrichment/Orsum/mmusculus_gmt_files/mmusculus.GO_BP.name.gmt' \
--files '/home/ag/Enrichment/Orsum/F_Chow_vs_F_HFD_2mo_GO_BP.txt' \
'/home/ag/Enrichment/Orsum/F_Chow_vs_F_HFD_3d_GO_BP.txt' \
'/home/ag/Enrichment/Orsum/F_HFD_2mo_vs_F_HFD_3d_GO_BP.txt' \
'/home/ag/Enrichment/Orsum/M_Chow_vs_F_Chow_GO_BP.txt' \
'/home/ag/Enrichment/Orsum/M_HFD_2mo_vs_F_HFD_2mo_GO_BP.txt' \
'/home/ag/Enrichment/Orsum/M_HFD_2mo_vs_M_HFD_3d_GO_BP.txt' \
'/home/ag/Enrichment/Orsum/M_HFD_3d_vs_F_HFD_3d_GO_BP.txt' \
--fileAliases 'F_Chow_vs_F_HFD_2mo_GO_BP' \
'F_Chow_vs_F_HFD_3d_GO_BP' \
'F_HFD_2mo_vs_F_HFD_3d_GO_BP' \
'M_Chow_vs_F_Chow_GO_BP' \
'M_HFD_2mo_vs_F_HFD_2mo_GO_BP' \
'M_HFD_2mo_vs_M_HFD_3d_GO_BP' \
'M_HFD_3d_vs_F_HFD_3d_GO_BP' \
--outputFolder '/home/ag/Enrichment/Orsum/Output_GO_BP'`

The log : [log.zip](https://github.com/ozanozisik/orsum/files/14178153/log.zip)

The resulting clustered heatmap : ![HeatmapClustered](https://github.com/ozanozisik/orsum/assets/5609985/09fea7a6-0b21-4469-b83b-0b9f1aa1cda8)

As you can see in the log : "F_Chow_vs_F_HFD_3d_GO_BP" is removed since it contains only 1 GO term
But it appears on the clusterd heatmap
And at the opposite :  "M_HFD_3d_vs_F_HFD_3d_GO_BP" is not present on the heatmap even though he should be there.
How to explain this? Did I make a mistake?

Thanks

**Comment by ozanozisik** [comment]
Hello, can you download the latest orsum repository and try that? I am sorry for the inconvenience.

**Comment by agroppi** [comment]
OK I'll try and let you know

**Comment by agroppi** [comment]
If I remove "F_Chow_vs_F_HFD_3d_GO_BP.txt" from the input files (and the corresponding filealias), the result seems to be correct : 
![HeatmapClustered](https://github.com/ozanozisik/orsum/assets/5609985/50aca91a-43c3-484a-8fda-5b27900a922f)

**Comment by ozanozisik** [comment]
This should be because of a bug that I fixed some time ago (311beb7fa00963180a6119606818c522f369f3d3) but have not updated on bioconda yet. If you download the code repository and try it, it should work. I will make a release very soon.

**Comment by agroppi** [comment]
I ran the version from the github code repository, but the bug is still there.

**Comment by ozanozisik** [comment]
Hello, if it won't be a problem, could you share the files with me from my inserm email address (ozan.ozisik) ?
Writing just in case, because I sometimes do this, if you are calling "orsum.py" instead of "python orsum.py" from the code folder, it will still run the installed version.

**Comment by agroppi** [comment]
Yes no problem. I'll send you the files.
And yes my command line started with `python3.9 orsum.py`
